name = "SpinitHelpers"
uuid = "6c799a6b-5c21-45a3-a415-36af85f1060b"
authors = ["Murari Soundararajan"]
version = "1.0.0-DEV"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
EzXML = "1.2.3"
JSON = "1.3.0"
TimeZones = "1.22.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
